name: GRAVITAS-ENTERPRISE-PIPELINE-1

trigger: none

pool: infra-agent

steps:
- task: TerraformTask@5
  displayName: TERRAFORM INIT
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'gravitas-connection'
    backendAzureRmOverrideSubscriptionID: 'c060d854-01c4-4739-baf7-57540765c3d2'
    backendAzureRmStorageAccountName: 'devstorage12'
    backendAzureRmContainerName: 'devcontainer'
    backendAzureRmKey: 'dev.tfstate'
- task: TerraformTask@5
  displayName: TERRAFORM VALIDATE
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
- task: TerraformTask@5
  displayName: TERRAFORM PLAN
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    environmentServiceNameAzureRM: 'gravitas-connection'